
services:
  app:
    container_name: app
    image: eventservice
    depends_on:
      - pg-local
      - migrate
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: always
    #It is useful to put depends_on to be sure that RabbitMQ is ready, if app does not handle connect retries.
  pg-local:
    container_name: pg-local
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    networks:
      - app-network
  migrate:
    image: migrate/migrate:v4.15.2
    container_name: migration
    depends_on:
      pg-local:
        condition: service_healthy
    command: [
      "-path=/app/migrations", # <---  Путь внутри контейнера
      "-database=postgres://postgres:1@pg-local:5432/postgres?sslmode=disable",
      "up"
    ]
    volumes:
      - ./internal/migrations:/app/migrations 
    networks:
      - app-network
networks:
  app-network:
    driver: bridge